[features]
seeds = false
[programs.localnet]
solana_twitter = "4AJz57EVRAXy4SLcE52BX1mP35ZrotL4xVLJ1j5Pfmi8"

[programs.devnet]
solana_twitter = "4AJz57EVRAXy4SLcE52BX1mP35ZrotL4xVLJ1j5Pfmi8"

[programs.mainnet]
solana_twitter = "4AJz57EVRAXy4SLcE52BX1mP35ZrotL4xVLJ1j5Pfmi8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/hakeemullah/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"


